using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Windows.ApplicationModel.DataTransfer;

namespace ClipboardHistoryWatcher;

/// <summary>
/// Headless console replacement for the PowerShell/WinRT-reflection clipboard bridge (which
/// failed silently — see .workspace round-2 plan). Ported from the user's known-working
/// command_center project (Synapse.Infrastructure/System/WindowsClipboardHistoryService.cs):
/// same InitializeComWrappers() + STAThread setup, same Contains()-based format classification,
/// same "copy the bitmap stream bytes as-is" approach for images (no PNG re-encode — if this
/// turns out not to be a valid PNG container in practice, that's the first thing to fix).
///
/// Emits one JSON object per line (NDJSON) to stdout, matching the ClipboardEntry shape used by
/// connectome-extensions/clipboard/src/common/clipboard-api.ts.
/// </summary>
internal static class Program
{
    private static readonly HashSet<string> Seen = new();
    private static string _cacheDir = string.Empty;

    [STAThread]
    private static async Task Main()
    {
        // Unlike the WinUI/Windows App SDK reference app, a plain console app targeting
        // net8.0-windows10.0.22621.0 gets Windows.ApplicationModel.DataTransfer.Clipboard's
        // CsWinRT projection auto-generated by the SDK for this single assembly, with no
        // separate WinRT.ComWrappersSupport.InitializeComWrappers() call needed — that call is
        // specifically for Windows App SDK's multi-assembly bootstrapping, not plain OS WinRT
        // namespaces like Clipboard.

        _cacheDir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "Connectome", "clipboard-cache");
        Directory.CreateDirectory(_cacheDir);
        CleanupCache();

        if (!Clipboard.IsHistoryEnabled())
        {
            EmitStatus("disabled");
            while (!Clipboard.IsHistoryEnabled())
            {
                await Task.Delay(5000);
            }
        }
        EmitStatus("running");

        Clipboard.HistoryChanged += async (_, _) => await PollAsync();

        while (true)
        {
            await PollAsync();
            // Re-assert running on each cycle so a late-connecting Electron renderer
            // still sees status even if the first EmitStatus was before any window existed.
            // (Main process also buffers, but this is cheap insurance.)
            EmitStatus("running");
            await Task.Delay(2000);
        }
    }

    private static async Task PollAsync()
    {
        try
        {
            var result = await Clipboard.GetHistoryItemsAsync();
            if (result.Status != ClipboardHistoryItemsResultStatus.Success)
            {
                return;
            }
            foreach (var item in result.Items)
            {
                await ProcessItemAsync(item);
            }
        }
        catch (Exception ex)
        {
            EmitError(ex.Message);
        }
    }

    private static async Task ProcessItemAsync(ClipboardHistoryItem item)
    {
        try
        {
            var view = item.Content;
            var timestamp = item.Timestamp.ToUnixTimeMilliseconds();

            if (view.Contains(StandardDataFormats.Text))
            {
                var text = await view.GetTextAsync();
                if (string.IsNullOrEmpty(text))
                {
                    return;
                }
                var id = "text:" + Hash(text);
                if (!Seen.Add(id))
                {
                    return;
                }
                Emit(new { id, type = "text", text, timestamp });
                return;
            }

            if (view.Contains(StandardDataFormats.StorageItems))
            {
                var storageItems = await view.GetStorageItemsAsync();
                var paths = storageItems.Select(i => i.Path).Where(p => !string.IsNullOrEmpty(p)).ToArray();
                if (paths.Length == 0)
                {
                    return;
                }
                var id = "file:" + Hash(string.Join("|", paths));
                if (!Seen.Add(id))
                {
                    return;
                }
                Emit(new { id, type = "file", paths, timestamp });
                return;
            }

            if (view.Contains(StandardDataFormats.Bitmap))
            {
                var reference = await view.GetBitmapAsync();
                using var stream = await reference.OpenReadAsync();
                byte[] streamBytes;
                using (var ms = new MemoryStream())
                using (var inputStream = stream.AsStreamForRead())
                {
                    await inputStream.CopyToAsync(ms);
                    streamBytes = ms.ToArray();
                }
                var hash = Convert.ToHexString(MD5.HashData(streamBytes));
                var fileName = $"{hash}.bmp";
                var id = "image:" + hash;
                if (!Seen.Add(id))
                {
                    return;
                }
                var filePath = Path.Combine(_cacheDir, fileName);
                if (!File.Exists(filePath))
                {
                    await File.WriteAllBytesAsync(filePath, streamBytes);
                    CleanupCache();
                }
                else
                {
                    try
                    {
                        File.SetLastWriteTimeUtc(filePath, DateTime.UtcNow);
                    }
                    catch {}
                }
                Emit(new { id, type = "image", cachedImagePath = filePath, timestamp });
            }
        }
        catch
        {
            // A format can disappear while history is changing — same gotcha noted in the
            // reference implementation. Skip this item and keep going.
        }
    }

    private static string Hash(string s)
    {
        var bytes = MD5.HashData(Encoding.UTF8.GetBytes(s));
        return Convert.ToHexString(bytes);
    }

    private static void Emit(object payload)
    {
        Console.WriteLine(JsonSerializer.Serialize(payload));
    }

    private static void EmitStatus(string status)
    {
        Emit(new
        {
            id = $"status:{status}",
            type = "status",
            text = status,
            timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()
        });
    }

    private static void EmitError(string message)
    {
        Emit(new
        {
            id = $"error:{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
            type = "error",
            text = message,
            timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()
        });
    }

    private static void CleanupCache()
    {
        try
        {
            var dirInfo = new DirectoryInfo(_cacheDir);
            var files = dirInfo.GetFiles("*.bmp")
                               .OrderByDescending(f => f.LastWriteTimeUtc)
                               .ToList();

            const int maxCacheFiles = 100;
            if (files.Count > maxCacheFiles)
            {
                for (int i = maxCacheFiles; i < files.Count; i++)
                {
                    try
                    {
                        files[i].Delete();
                    }
                    catch
                    {
                        // File might be locked or already deleted
                    }
                }
            }
        }
        catch
        {
            // Best effort
        }
    }
}
